### ISSUE TITLE
Can I transmit to Dolibarr the contacts acquired in a different category than "third parties"?

### ISSUE THREAD

**Issue by stxw** [ViralAgency/Dolipress#1]
Hello, i dont find info ?

**Comment by ViralAgency** [comment]
Hi,
at the current version it is not possible. However, if you let me know where you would like to move them, we can tell you what to change to achieve your purpose. In any case, in the next releases we will implement this choice.

**Comment by stxw** [comment]
Hello, here is my problem.

I have an association and people can register for an event or to become a member.

I therefore wish that the 2 registrations be on Dolibarr but that I can differentiate them.

 

Ideally have 2 forms.

1 who becomes a tier on dolibarr

1 who becomes a subscriber.

 

But I take any offer.

 

Thank you very much for your intermission.

 

Have a good day

**Comment by ViralAgency** [comment]
The quickest solution is to create 2 registration forms, 1 of which is connected to Dolibarr. In fact currently the plugin only supports 1 registration form.  From the code it is possible to change the API destination by choosing from the following:

- BankAccounts
- Contacts
- Documents
- Invoices
- Login
- Poposals
- Setup
- Status
- Thirdparties
- Tickets
- Users

Obviously many of these do not apply to you.  During the development of the plugin we considered that the best thing was to interface contacts with third parties, however this option can be changed simply by changing the "URL" string in the plugin settings in the Dolipress Control Panel.

For example, if you want the data to be saved in "Contacts" you just need to change the URL, from https://www.yourdomain.com/htdocs/api/index.php/thirdparties to https://www.yourdomain.com/htdocs//api/index.php/contacts

Obviously the data you transmit must be compatible with the Dolibarr type.

If you think you might need configuration assistance, alternatively, we can work on it by creating a custom solution, but for a fee.

**Comment by stxw** [comment]
Ok, so is it possible that it comes on Members ?

 

htdocs/adherents/class/adherent.class.php.

 

(https://wiki.dolibarr.org/index.php?title=Module_Adh%C3%A9rents_(d%C3%A9veloppeur))

 

with name , address, email, phone ?

 

De : Luca Scandroglio ***@***.***> 
Envoyé : mercredi, 27 avril 2022 13:01
À : ViralAgency/Dolipress ***@***.***>
Cc : stxw ***@***.***>; Author ***@***.***>
Objet : Re: [ViralAgency/Dolipress] Can I transmit to Dolibarr the contacts acquired in a different category than "third parties"? (Issue #1)

 

The quickest solution is to create 2 registration forms, 1 of which is connected to Dolibarr. In fact currently the plugin only supports 1 registration form. From the code it is possible to change the API destination by choosing from the following:

*	BankAccounts
*	Contacts
*	Documents
*	Invoices
*	Login
*	Poposals
*	Setup
*	Status
*	Thirdparties
*	Tickets
*	Users

Obviously many of these do not apply to you. During the development of the plugin we considered that the best thing was to interface contacts with third parties, however this option can be changed simply by changing the "URL" string in the plugin settings in the Wordpress plugin backend.

For example, if you want the data to be saved in "Contacts" you just need to change the URL, from https://www.yourdomain.com/htdocs/api/index.php/thirdparties to https://www.yourdomain.com /htdocs//api/index.php/users

Obviously the data you transmit must be compatible with the Dolibarr type.

If you think you might need configuration assistance, alternatively, we can work on it by creating a custom solution, but for a fee.
